extends: default

rules:
  truthy:
    check-keys: true
    allowed-values: ["true", "false"]
  line-length:
    max: 120
    level: warning
  document-start: disable
  comments:
    min-spaces-from-content: 1
