"""The interconnect module -- white matter, spec `docs/design/INTERCONNECT-MODULE-SPEC.md`.

Re-exports the public surface of every file under this package (spec section 2.1
Table 2's ten files) so a caller can `from cogsyndelta.interconnect import WhiteMatter`
rather than reaching into each submodule directly. Owned by lane IC-8 (Table 2's
`__init__.py` row: "re-exports; `__all__` is the public surface").
"""

from __future__ import annotations

from cogsyndelta.interconnect.adapters import (
    ConditioningPrefix,
    RegionAdapter,
    TopKSelect,
    assert_float_tract,
)
from cogsyndelta.interconnect.controller import (
    ControllerConfigError,
    ControllerOutput,
    ControllerParticipant,
    FlooredSimplex,
    ThalamicController,
    box_integerise,
)
from cogsyndelta.interconnect.episodic import (
    GPU_RESIDENT_BONUS,
    MAX_IN_FLIGHT,
    CapacityBranch,
    CapacityDecision,
    EpisodicStoreImpl,
    HostVram,
    InMemoryBackend,
    Lifecycle,
    Residency,
    SchedulerBudgets,
    SqliteBackend,
    StoreBackend,
    StoreBackpressureError,
    StoredRecord,
    StoreDurabilityError,
    StoreLifecycleError,
    TierBudget,
    capacity_decision,
    partition_scope_key,
    probe_host_vram,
    staleness_penalty,
)
from cogsyndelta.interconnect.episodic_store import (
    ContractGap,
    EpisodicStore,
    InMemoryStoreStub,
    Scope,
    StoreScopeError,
    WriteReceipt,
    derive_scope,
)
from cogsyndelta.interconnect.gates import (
    POINT,
    GateFailure,
    check_attention_mass_floor,
    check_frozen_set_identity,
    check_null_gate,
    check_overfit_gate,
    check_phase_d_revert,
    check_topology_agreement,
    check_write_back_gate,
)
from cogsyndelta.interconnect.kv_bank import STORE_PARTICIPANT, KVBank, StoreProjection
from cogsyndelta.interconnect.losses import DistilLoss, FlopsPenalty, RankLoss, UnifyLoss
from cogsyndelta.interconnect.mind import (
    InterconnectConfig,
    InterconnectConfigError,
    ParticipantSpec,
    WhiteMatter,
    WhiteMatterOutput,
)
from cogsyndelta.interconnect.phase_a import (
    PHASE_A_TRAINABLE_R5,
    TABLE_4_TOTAL_R5,
    PhaseABatch,
    PhaseAConfig,
    PhaseAGuardReport,
    PhaseAResult,
    PhaseATrainer,
    StepRecord,
    check_phase_a_frozen_set,
    loss_decreased,
    phase_a_guards,
    phase_a_parameter_partition,
)
from cogsyndelta.interconnect.readout import FrontalReadout, NullCandidate, RankHead, UnifyProbes
from cogsyndelta.interconnect.receipts import ComposeReceipt
from cogsyndelta.interconnect.schedule import (
    CODEC_V1,
    FORBIDDEN_KEYS,
    PRECISIONS,
    OutputSpec,
    ParticipantBudget,
    Schedule,
    ScheduleNode,
    ScheduleValidator,
    ScheduleValidatorConfigError,
    ScheduleViolationError,
    StepBudget,
)
from cogsyndelta.interconnect.workspace import LatentBank, Workspace, WorkspaceBlock

__all__ = [
    "CODEC_V1",
    "FORBIDDEN_KEYS",
    "GPU_RESIDENT_BONUS",
    "MAX_IN_FLIGHT",
    "PHASE_A_TRAINABLE_R5",
    "POINT",
    "PRECISIONS",
    "STORE_PARTICIPANT",
    "TABLE_4_TOTAL_R5",
    "CapacityBranch",
    "CapacityDecision",
    "ComposeReceipt",
    "ConditioningPrefix",
    "ContractGap",
    "ControllerConfigError",
    "ControllerOutput",
    "ControllerParticipant",
    "DistilLoss",
    "EpisodicStore",
    "EpisodicStoreImpl",
    "FlooredSimplex",
    "FlopsPenalty",
    "FrontalReadout",
    "GateFailure",
    "HostVram",
    "InMemoryBackend",
    "InMemoryStoreStub",
    "InterconnectConfig",
    "InterconnectConfigError",
    "KVBank",
    "LatentBank",
    "Lifecycle",
    "NullCandidate",
    "OutputSpec",
    "ParticipantBudget",
    "ParticipantSpec",
    "PhaseABatch",
    "PhaseAConfig",
    "PhaseAGuardReport",
    "PhaseAResult",
    "PhaseATrainer",
    "RankHead",
    "RankLoss",
    "RegionAdapter",
    "Residency",
    "Schedule",
    "ScheduleNode",
    "ScheduleValidator",
    "ScheduleValidatorConfigError",
    "ScheduleViolationError",
    "SchedulerBudgets",
    "Scope",
    "SqliteBackend",
    "StepBudget",
    "StepRecord",
    "StoreBackend",
    "StoreBackpressureError",
    "StoreDurabilityError",
    "StoreLifecycleError",
    "StoreProjection",
    "StoreScopeError",
    "StoredRecord",
    "ThalamicController",
    "TierBudget",
    "TopKSelect",
    "UnifyLoss",
    "UnifyProbes",
    "WhiteMatter",
    "WhiteMatterOutput",
    "Workspace",
    "WorkspaceBlock",
    "WriteReceipt",
    "assert_float_tract",
    "box_integerise",
    "capacity_decision",
    "check_attention_mass_floor",
    "check_frozen_set_identity",
    "check_null_gate",
    "check_overfit_gate",
    "check_phase_a_frozen_set",
    "check_phase_d_revert",
    "check_topology_agreement",
    "check_write_back_gate",
    "derive_scope",
    "loss_decreased",
    "partition_scope_key",
    "phase_a_guards",
    "phase_a_parameter_partition",
    "probe_host_vram",
    "staleness_penalty",
]
