#!/usr/bin/env python3
"""Print the CORPUS-CONTRACT.md admission checklist for one factory-fetched dataset.

WHAT THIS DOES AND DOES NOT DO
This is a read-only gate, not a fetcher and not a corpus mutator. It reads one dataset
factory `provenance.json` (see program/datasets/README.md `S2`) plus a target CSD region
name, and prints five checks: licence tier vs. the region's already-declared tier,
provenance-group share against CORPUS-CONTRACT.md's B1 (<= 0.40 post-admission),
`verification_status == VERIFIED`, (check 4) a second, independent read of the full
catalogue row's own structural refusal signals, and (check 5) whether `provenance.json`'s
own `admission` block (`policy_version` and `constants`, once the factory writes one)
agrees with this tool's pinned policy constants. It does not touch CORPUS-CONTRACT.md,
csd-regions.json,
or any region's fetch list -- admitting a dataset for real is a human/agent action taken
after reading this tool's output, same discipline as csd-corpus-expand.py's structural
REFUSE gate (no override flag) but advisory rather than fetch-blocking, because this tool
runs after the fetch, not during it.

TASK A COORDINATION (round-3 review, closing check 5's structural-drift defect)
`ADAPTER_POLICY_CONSTANTS` below is not hand-transcribed. It is the exact key set and
values of `dataset_factory.admission.admission_constants()` as the factory COMMITS them,
`ADMISSION_POLICY_VERSION` included as a MEMBER of the dict rather than a sibling of it.
Hand-transcription is what produced the defect: this tool once pinned six lower_snake
keys against the factory's fourteen UPPER_SNAKE ones (key overlap: zero) and a
differently-punctuated version string, so `constants != ADAPTER_POLICY_CONSTANTS` failed
on every real record and check 5 refused every landed dataset with a constant, contentless
refusal. An intermediate fix closed the vocabulary half but kept the version outside the
dict, which still failed by exactly one key once the factory landed it inside; this is
the reconciled state, verified against a record the committed factory actually writes.

`tests/fixtures/dataset-factory-policy.json` is now GENERATED by the factory itself --
`dataset-factory policy-constants --out <path>` -- rather than transcribed, so the pinned
fixture is literally factory output. The command exists for this purpose; regenerate,
never edit by hand, and re-verify `ADAPTER_POLICY_CONSTANTS` against the regenerated file
(`test_adapter_policy_constants_match_pinned_fixture` fails if you forget).
`test_pinned_fixture_matches_live_factory_output_when_available` additionally re-imports
the real factory module (skipping when the sibling `dataset-factory` checkout is absent)
and requires FULL equality with `admission_constants()`, not a subset: a key the factory
has ADDED that this tool does not pin is precisely how the version key slipped through
once already, so it now fails rather than being tolerated. `check_policy_constants_drift`
(check 5) stays forward-compatible in the one direction that is safe: it PASSES with a
note when `provenance.json` carries no `admission` block at all (a record fetched before
the factory started emitting one), and only FAILs on an observable drift -- a
present-but-disagreeing `admission.policy_version`, a record whose two copies of the
version disagree with each other, and/or a differing `admission.constants`.

WHY THE LICENCE-TIER TABLE IS DUPLICATED HERE, NOT IMPORTED
scripts/csd-publish-checkpoint.py's LICENCE_TIER is the source of truth for what a region
is licensed under today. Importing it would couple this admission tool to the publish
script's module surface (and its torch/HF-hub-adjacent import chain) for the sake of one
small dict. The table is small, dated, and rarely changes; it is transcribed here with a
test (test_licence_tier_matches_publish_checkpoint) that fails loudly the day the two
tables disagree, which is a cheaper and more honest coupling than an import that pulls in
unrelated machinery for four rows.

CHECK 4 IS A SECOND, INDEPENDENT LOOK -- NOT A RE-READ OF THE SAME FIELDS
Checks 1-3 read only what the factory's `provenance.json` actually emits per dataset
(verdict, verification_status, provenance_group, total_bytes/file_count/file_manifest,
licence_* and a trimmed `catalogue_entry`). That trimmed entry carries `grant_scope` but
NOT `redistribute{nc,sa,nd,attribution}`, `provenance_red_flags`, or
`enrichment_licence_result` -- confirmed by reading every real provenance.json under
/mnt/bulk/csd-corpus/factory-2026-09-03/ (2026-09-03 ground pass), all of which trim
`catalogue_entry` to the same six keys. Those three fields only exist in the full
catalogue row (`docs/design/datasets/catalogue-2026-09-03.json`, keyed by `repo_id`), which
is also where the factory's OWN gate (`admission.check_admission`) failed to read them
(ground-pass findings B1-B3: narrativeqa and BeIR/cqadupstack both landed on /bulk despite
carrying a structural refusal in exactly these fields). Check 4 therefore loads that
catalogue independently and applies its own refusal logic against it, so a defect in the
factory's gate does not silently pass through this one too -- two gates reading two
different sources of truth, not one gate re-reading the same file.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

_SRC = str(Path(__file__).resolve().parents[1] / "src")
if _SRC not in sys.path:
    # cogsyndelta.regions.aliases has no heavy dependency -- see
    # scripts/csd-train-all.py's identical shim for the full reasoning.
    sys.path.append(_SRC)

from cogsyndelta.regions.aliases import canonical_region  # noqa: E402

# Transcribed from scripts/csd-publish-checkpoint.py's LICENCE_TIER, restricted to the
# ordering that matters here: how strict a tier is, not which regions exist. Kept in sync
# by test_licence_tier_matches_publish_checkpoint. Keyed CANONICALLY (`language`, not
# `code`; `visual`, not `vl_latent`) to match LICENCE_TIER exactly; check_licence_tier()
# resolves its `region` argument through canonical_region() first.
TIER_ORDER: tuple[str, ...] = ("mit", "cc-by-sa-4.0", "cc-by-nc-sa-4.0")

REGION_TIER: dict[str, str] = {
    "language": "mit",
    "classify_banking77": "mit",
    "classify_go_emotions": "mit",
    "reason": "mit",
    "visual": "mit",
    "compress": "cc-by-sa-4.0",
    "retrieve": "cc-by-nc-sa-4.0",
    "memory": "cc-by-nc-sa-4.0",
    "composed": "cc-by-nc-sa-4.0",
    "cogsyndelta": "cc-by-nc-sa-4.0",
}

# Catalogue verdict -> the licence tier that verdict requires of the region it joins.
# REFUSE/BLOCKING/UNVERIFIED have no tier: they are inadmissible outright, independent of
# any region's current tier, so they map to None rather than to a value TIER_ORDER ranks.
VERDICT_TIER: dict[str, str | None] = {
    "PERMISSIVE_OK": "mit",
    "ATTRIBUTION": "mit",
    "SHARE_ALIKE": "cc-by-sa-4.0",
    "NC": "cc-by-nc-sa-4.0",
    "REFUSE": None,
    "BLOCKING": None,
    "UNVERIFIED": None,
}

B1_MAX_SHARE = 0.40

# g9-kaggle/PROCESS.md §1 plus admission-round held_seed/aux: only `train` contributes
# to provenance-group concentration. A missing role on a legacy factory record is
# treated as train (those records never carried the field). Explicit non-train roles
# are excluded even if they would dominate by `total_bytes`.
TRAIN_ROLE = "train"
EXCLUDED_CONCENTRATION_ROLES: frozenset[str] = frozenset({"probe", "aux", "refuse", "held_seed"})

# docs/design/DATASET-FACTORY-CATALOGUE-2026-09-03.md S8: "4 bytes per token" for text
# measured on disk, the catalogue's own stated INFERRED assumption for row/token
# estimates. Real provenance.json never emits `row_count`/`count` (confirmed against
# every dataset fetched 2026-09-03) -- this is the fallback, and every result computed
# from it is labelled ESTIMATED so it is never mistaken for a factory-measured count.
BYTES_PER_TOKEN = 4

# grant_scope values (docs/design/datasets/catalogue-2026-09-03.json note 3, plus the
# survey's `code_only`/`metadata_only`) that cover the dataset's actual text/content for
# training use. Anything else (`code_only`: only code/annotation layer is licensed, not
# the underlying text; `metadata_only`: only bibliographic metadata; `database_rights_only`:
# only the compilation/database right, not the individual contents -- allenai/wildguardmix's
# real grant, ODC-By ss2.4) means the grant does NOT cover what a corpus admission would
# actually emit -- structurally inadmissible regardless of the catalogue's `verdict`, per
# B1's narrativeqa finding.
#
# MUST equal `dataset_factory.admission.FULL_CONTENT_GRANT_SCOPES` in the factory repo
# exactly (round-2 review B4: this set used to also admit `database_rights_only`, which
# the factory's own gate refuses -- wildguardmix ADMITted through this tool while the
# factory refused it, a live split-brain). `test_full_content_grant_scopes_matches_fixture`
# pins it against tests/fixtures/dataset-factory-policy.json so a future edit that widens
# (or narrows) either side alone fails loudly instead of drifting again.
FULL_CONTENT_GRANT_SCOPES: frozenset[str] = frozenset(
    {"whole_corpus", "whole_corpus (heterogeneous per file)"}
)

# `redistribute` flags that hard-forbid training/redistribution with no override, mirrored
# from `dataset_factory.admission.FORBIDDEN_REDISTRIBUTE_FLAGS` exactly (see the drift
# fixture above) -- "nd" (No-Derivatives) forbids producing a derivative work at all, and
# training a model on the content is exactly that.
FORBIDDEN_REDISTRIBUTE_FLAGS: frozenset[str] = frozenset({"nd"})

# Marks a structural refusal inside `enrichment_licence_result` (and, mirroring the
# factory's `_has_enrichment_refusal_marker`, `enrichment_plan`) prose. Transcribed
# VERBATIM from `dataset_factory.admission.ENRICHMENT_REFUSAL_MARKER_RE` /
# `ENRICHMENT_NONE_ADMISSIBLE_MARKER` -- deliberately CASE-SENSITIVE, matching only the
# catalogue's own shouting-case authoring convention ("R9 REFUSE AT INGEST", "NONE
# ADMISSIBLE TODAY") rather than ordinary lower-case prose that merely discusses refusal
# elsewhere ("refused at ingest (R4)" as a sub-clause note). Round-2 review found this
# tool matching case-INSENSITIVELY instead, disagreeing with the factory on 3 catalogue
# rows -- this is the fix.
ENRICHMENT_REFUSAL_MARKER_RE = re.compile(r"\bREFUSE[SD]?\b")
ENRICHMENT_NONE_ADMISSIBLE_MARKER = "NONE ADMISSIBLE"

# A `provenance_red_flags` entry counts as UNRESOLVED unless
# `provenance_red_flags_resolution` (a list of {"flag": <exact red-flag text>, "resolved":
# bool, ...}) carries an entry for that exact flag text with resolved=True. This mirrors
# `dataset_factory.admission.unresolved_red_flags`/`red_flag_resolution_matches` (already
# committed on the factory side) exactly -- prose documentation only, not itself part of
# the pinned drift-check dict below (the factory's `admission_constants()` expresses the
# same rule as the two booleans `RED_FLAGS_BLOCK_ADMISSION`/`RED_FLAG_RESOLVED_MARKER`
# inside `ADAPTER_POLICY_CONSTANTS`, not as a prose string) -- see `_unresolved_red_flags`.
RED_FLAG_RESOLUTION_RULE = (
    "a provenance_red_flags entry is unresolved unless provenance_red_flags_resolution "
    "carries an entry for it with resolved=true"
)

# `dataset_factory.catalogue.GRANT_SCOPE_CLASSES` transcribed verbatim -- the full closed
# vocabulary `grant_scope` may take, of which `FULL_CONTENT_GRANT_SCOPES` above is the
# admissible subset. Not read by any check in this tool (checks 4/5 only need the
# admissible subset and the raw value for its error message) -- pinned here purely so it
# is part of the `ADAPTER_POLICY_CONSTANTS` drift comparison, since it is part of the
# factory's own `admission_constants()` output.
GRANT_SCOPE_CLASSES: frozenset[str] = frozenset(
    {
        "whole_corpus",
        "whole_corpus (heterogeneous per file)",
        "metadata_only",
        "code_only",
        "database_rights_only",
        "unstated",
    }
)

# `dataset_factory.admission.ADMISSION_POLICY_VERSION` transcribed verbatim from the
# factory repo's HEAD commit (see the module docstring's TASK A COORDINATION note).
# Compared SEPARATELY against `provenance.json`'s top-level `admission.policy_version` by
# `check_policy_constants_drift` -- a normalised-subset agreement with the factory's
# committed `admission_decision()` shape (`policy_version` as a sibling of `constants`,
# not nested inside it), deliberately chosen over pinning against an in-flight, uncommitted
# edit to a dict this tool does not own.
POLICY_VERSION = "2026-09-03.r3"

# The full set of pinned policy constants, TRANSCRIBED VERBATIM (same keys, same values)
# from a live read of `dataset_factory.admission.admission_constants()` at the factory
# repo's HEAD commit -- not hand-typed to agree with this tool's own prior guess, which is
# what let the two sides disagree on both vocabulary and version string with nothing able
# to detect it (round-3 review, finding 1). `tests/fixtures/dataset-factory-policy.json`
# is regenerated the same way; `test_adapter_policy_constants_match_pinned_fixture` pins
# this dict against that fixture, and
# `test_pinned_fixture_matches_live_factory_output_when_available` pins it against the
# real factory module directly (as a subset -- see that test's docstring) when the sibling
# checkout is present. Constants with no direct gate in this tool (`ADMISSIBLE_VERDICTS`,
# `REQUIRED_VERIFICATION_STATUS`, `EVAL_ONLY_TAG`, `NC_VERDICT`, `REDISTRIBUTE_NC_FLAG`,
# `RED_FLAGS_BLOCK_ADMISSION`, `RED_FLAG_RESOLVED_MARKER`, `SCHEMA_DEFECTS_BLOCK_ADMISSION`,
# `REQUIRE_LICENCE_TEXT`) are still pinned here even though checks 1-3 apply their own
# separately-maintained REGION_TIER/VERDICT_TIER tables covering related ground -- this
# dict's only job is to detect drift against `admission.constants`, not to be this tool's
# own source of gating logic for those fields.
ADAPTER_POLICY_CONSTANTS: dict[str, Any] = {
    # `ADMISSION_POLICY_VERSION` is a MEMBER of this dict, not a sibling of it, because
    # that is where the factory's committed `admission_constants()` puts it. This was the
    # last live half of the round-3 split-brain: the factory landed the version inside the
    # constants (its own review finding: keeping it in the compared dict makes "same
    # constants, different policy generation" unrepresentable) while this tool pinned the
    # other fourteen keys and compared the version separately -- so `constants !=
    # ADAPTER_POLICY_CONSTANTS` failed by exactly one key on every real record, and check 5
    # still refused every landed dataset. The separate comparison against the record's
    # top-level `admission.policy_version` is KEPT below, and now also cross-checks this
    # member against it: a record whose two copies of the version disagree is internally
    # inconsistent on the factory's side, and that is worth reporting on its own terms.
    "ADMISSION_POLICY_VERSION": POLICY_VERSION,
    "ADMISSIBLE_VERDICTS": sorted({"PERMISSIVE_OK", "ATTRIBUTION", "SHARE_ALIKE", "NC"}),
    "REQUIRED_VERIFICATION_STATUS": "VERIFIED",
    "EVAL_ONLY_TAG": "EVAL-ONLY",
    "NC_VERDICT": "NC",
    "REDISTRIBUTE_NC_FLAG": "nc",
    "FULL_CONTENT_GRANT_SCOPES": sorted(FULL_CONTENT_GRANT_SCOPES),
    "FORBIDDEN_REDISTRIBUTE_FLAGS": sorted(FORBIDDEN_REDISTRIBUTE_FLAGS),
    "RED_FLAGS_BLOCK_ADMISSION": True,
    "RED_FLAG_RESOLVED_MARKER": True,
    "SCHEMA_DEFECTS_BLOCK_ADMISSION": True,
    "REQUIRE_LICENCE_TEXT": True,
    "ENRICHMENT_REFUSAL_MARKER_RE": ENRICHMENT_REFUSAL_MARKER_RE.pattern,
    "ENRICHMENT_NONE_ADMISSIBLE_MARKER": ENRICHMENT_NONE_ADMISSIBLE_MARKER,
    "GRANT_SCOPE_CLASSES": sorted(GRANT_SCOPE_CLASSES),
}

DEFAULT_CATALOGUE_PATH = (
    Path(__file__).resolve().parents[1]
    / "docs"
    / "design"
    / "datasets"
    / "catalogue-2026-09-03.json"
)


@dataclass(frozen=True)
class CheckResult:
    name: str
    passed: bool
    detail: str


def check_licence_tier(verdict: str, region: str, region_tier: dict[str, str]) -> CheckResult:
    """Check 1: the dataset's verdict must not demand a stricter tier than the region has.

    A region tier not in `region_tier` at all is treated as unknown, matching
    csd-publish-checkpoint.py's stated discipline of refusing rather than guessing a
    licence for an unaudited region -- an unknown region tier FAILs here too, loudly,
    rather than silently defaulting to `mit`.

    `region` is resolved through `canonical_region` first, so `--region code` and
    `--region language` (cogsyndelta.regions.aliases) look up the identical entry in
    `region_tier`, which is keyed canonically.
    """
    required = VERDICT_TIER.get(verdict)
    if required is None:
        return CheckResult(
            "licence_tier",
            False,
            f"verdict={verdict!r} is inadmissible outright (REFUSE/BLOCKING/UNVERIFIED "
            "carry no tier)",
        )
    current = region_tier.get(canonical_region(region))
    if current is None:
        return CheckResult(
            "licence_tier",
            False,
            f"region {region!r} has no declared tier in REGION_TIER -- refusing rather "
            "than guessing (residual_mlp/stream_vae are the known unaudited regions)",
        )
    if current not in TIER_ORDER or required not in TIER_ORDER:
        return CheckResult(
            "licence_tier",
            False,
            f"unranked tier: region tier={current!r}, required tier={required!r}",
        )
    if TIER_ORDER.index(required) <= TIER_ORDER.index(current):
        return CheckResult(
            "licence_tier",
            True,
            f"verdict {verdict!r} requires tier {required!r}, region {region!r} already "
            f"at {current!r} -- no upgrade needed",
        )
    return CheckResult(
        "licence_tier",
        False,
        f"verdict {verdict!r} requires tier {required!r}, stricter than region {region!r}'s "
        f"current {current!r} -- requires an EXPLICIT tier upgrade (Rider-1-style), not "
        "silent admission",
    )


def landing_role(provenance: dict[str, Any]) -> str | None:
    """Landing role from provenance.json: top-level `role`, else `catalogue_entry.role`.

    None means the record predates the field (g9 PROCESS.md / factory regenerate) and is
    treated as train for concentration. Do not parse `why` prose.
    """
    raw = provenance.get("role")
    if raw is None:
        entry = provenance.get("catalogue_entry")
        if isinstance(entry, dict):
            raw = entry.get("role")
    if raw is None or raw == "":
        return None
    return str(raw)


def contributes_to_train_concentration(role: str | None) -> bool:
    """True for `train` and for a missing role (legacy records). False for every other
    explicit role, including probe/aux/refuse/held_seed."""
    if role is None:
        return True
    return role == TRAIN_ROLE


def largest_source(shares: dict[str, int]) -> tuple[str, float]:
    """`(group, share)` of the group with the most rows. `("", 0.0)` when empty."""
    total = sum(shares.values())
    if total <= 0 or not shares:
        return "", 0.0
    group = max(shares, key=lambda g: shares[g])
    return str(group), shares[group] / total


def check_b1_share(
    provenance_group: str,
    added_count: int,
    existing_shares: dict[str, int],
    max_share: float = B1_MAX_SHARE,
    estimated: bool = False,
    measure_note: str = "",
) -> CheckResult:
    """Check 2: post-admission share of `provenance_group` must stay <= B1's 0.40 cap.

    Computed on provenance groups, per CORPUS-CONTRACT.md -- the caller is responsible for
    passing `existing_shares` keyed by provenance group, not by dataset name or shard.
    `estimated=True` (see `resolve_added_count`) means `added_count` was derived from
    `total_bytes` rather than read from a factory-emitted row/token count, and the detail
    string says so -- the share number is only ever as trustworthy as that count.

    The refuse rule is unchanged: FAIL iff this group's post-admission share exceeds
    `max_share`. The detail also names the largest source in the post-admission mix
    (its share and the cap) so a run reports concentration even when a different group
    is the one that dominates.
    """
    if added_count < 0:
        return CheckResult("b1_share", False, f"added_count={added_count} is negative")
    total_before = sum(existing_shares.values())
    total_after = total_before + added_count
    if total_after <= 0:
        return CheckResult("b1_share", False, "post-admission corpus would have zero rows")
    group_after = existing_shares.get(provenance_group, 0) + added_count
    share = group_after / total_after
    passed = share <= max_share
    count_note = " [ESTIMATED from total_bytes]" if estimated else ""
    if measure_note:
        count_note = f"{count_note} [{measure_note}]"
    post = dict(existing_shares)
    post[provenance_group] = group_after
    largest_group, largest = largest_source(post)
    detail = (
        f"group={provenance_group!r} share after admission = {share:.4f} "
        f"({group_after}/{total_after}), cap={max_share}{count_note}; "
        f"largest source={largest_group!r} share={largest:.4f} cap={max_share}"
    )
    return CheckResult("b1_share", passed, detail)


def resolve_added_count(provenance: dict[str, Any]) -> tuple[int, bool]:
    """Resolve the row/token count this admission would add, and whether it is a real
    factory-emitted count or a fallback estimate.

    Prefers an explicit `row_count` or `count` field -- neither is emitted by the real
    dataset-factory `provenance.json` today (B4: every fetched-dataset provenance.json
    under /mnt/bulk/csd-corpus/factory-2026-09-03/ carries `total_bytes`/`file_count`/
    `file_manifest` but no row or token count), so falling through to that branch is
    expected on real input, not a bug. The estimate divides `total_bytes` by
    `BYTES_PER_TOKEN`, the catalogue's own stated assumption -- returns `(0, False)` when
    neither a count nor `total_bytes` is present, same as the prior always-zero behaviour,
    so a provenance.json missing everything still fails B1 loudly (0 rows added, 0 share)
    rather than crashing.
    """
    for key in ("row_count", "count"):
        value = provenance.get(key)
        if value is not None:
            return int(value), False
    total_bytes = provenance.get("total_bytes")
    if total_bytes is None:
        return 0, False
    return int(total_bytes) // BYTES_PER_TOKEN, True


def resolve_concentration_count(provenance: dict[str, Any]) -> tuple[int, bool, str]:
    """Row/image count that this landing contributes to B1 concentration.

    Non-train roles (probe, aux, refuse, held_seed, and any other explicit non-train
    token) contribute 0. When `active_train_set.train_files` is present (g24), that
    image count is used rather than `total_bytes`. Otherwise the existing
    `resolve_added_count` fallback applies, and the note records that
    `active_train_set` was absent.
    """
    role = landing_role(provenance)
    if not contributes_to_train_concentration(role):
        return 0, False, f"role={role!r} excluded from train concentration"
    ats = provenance.get("active_train_set")
    if isinstance(ats, dict) and ats.get("train_files") is not None:
        return int(ats["train_files"]), False, "active_train_set.train_files"
    count, estimated = resolve_added_count(provenance)
    return count, estimated, "active_train_set absent"


def check_verified(verification_status: str) -> CheckResult:
    """Check 3: only a fresh VERIFIED read is admissible.

    CONTRADICTED, UNVERIFIABLE and REFUSED-CLOSED are all inadmissible regardless of the
    `verdict` field -- an entry does not get readmitted by re-running this checklist on
    stale evidence, only by a new primary read that flips verification_status itself.
    """
    passed = verification_status == "VERIFIED"
    return CheckResult(
        "verification_status",
        passed,
        f"verification_status={verification_status!r} "
        f"({'admissible' if passed else 'inadmissible regardless of verdict'})",
    )


def repo_id_of(provenance: dict[str, Any]) -> str:
    """The dataset's repo_id, from a top-level field (older/synthetic provenance shapes,
    e.g. this module's own test fixtures) or from the real factory shape's trimmed
    `catalogue_entry.repo_id` (every real provenance.json under
    /mnt/bulk/csd-corpus/factory-2026-09-03/ has no top-level `repo_id` at all)."""
    repo_id = provenance.get("repo_id")
    if repo_id:
        return str(repo_id)
    return str(provenance.get("catalogue_entry", {}).get("repo_id", "<unknown repo_id>"))


def load_catalogue_index(path: Path) -> dict[str, dict[str, Any]]:
    """Load `docs/design/datasets/catalogue-2026-09-03.json` (schema
    csd-dataset-factory-catalogue/v1) into a repo_id -> full catalogue row index, for
    check_catalogue_structural_refusals. This is the FULL row -- `grant_scope`,
    `redistribute`, `provenance_red_flags`, `enrichment_licence_result` included -- not
    the trimmed `catalogue_entry` a provenance.json carries.
    """
    data = _load_json(path)
    index: dict[str, dict[str, Any]] = {}
    for entry in data.get("entries", []):
        repo_id = entry.get("repo_id")
        if repo_id:
            index[str(repo_id)] = entry
    return index


def _has_enrichment_refusal_marker(*texts: str) -> bool:
    """True if any of `texts` carries the catalogue's shouting-case structural-refusal
    marker convention -- transcribed from the factory's `_has_enrichment_refusal_marker`
    (checks `enrichment_licence_result` AND `enrichment_plan`, same as here)."""
    for text in texts:
        if ENRICHMENT_REFUSAL_MARKER_RE.search(text):
            return True
        if ENRICHMENT_NONE_ADMISSIBLE_MARKER in text:
            return True
    return False


def _unresolved_red_flags(red_flags: list[str], resolution: list[dict[str, Any]]) -> list[str]:
    """Which of `red_flags` are unresolved, per RED_FLAG_RESOLUTION_RULE: a flag counts as
    unresolved unless `resolution` (the catalogue row's `provenance_red_flags_resolution`)
    carries an entry whose `flag` equals it exactly and whose `resolved` is `True`.

    An entry that is not a dict, or whose `resolved` is anything other than the literal
    `True` (a truthy string, a missing key, `False`), does not count -- resolution is an
    explicit, structural marker, not something this tool infers from a resolution entry
    merely existing for that flag.
    """
    resolved_flags = {
        entry.get("flag")
        for entry in resolution
        if isinstance(entry, dict) and entry.get("resolved") is True
    }
    return [flag for flag in red_flags if flag not in resolved_flags]


def check_catalogue_structural_refusals(
    repo_id: str, catalogue_index: dict[str, dict[str, Any]]
) -> CheckResult:
    """Check 4 (second, independent look): apply the catalogue row's own structural
    refusal signals, cross-referenced by `repo_id` -- the same fields the factory's
    `admission.check_admission` parses into provenance.json but never gated on (ground-
    pass B3), read here from the catalogue directly rather than trusted from provenance.

    A repo_id absent from the catalogue index FAILS closed (refusing rather than
    admitting an entry this check cannot evaluate), matching check_licence_tier's
    discipline for an unaudited region.

    Refusal signals, each independently sufficient:
      - `grant_scope` not in FULL_CONTENT_GRANT_SCOPES (B1: narrativeqa's `code_only`
        licenses the annotation/code layer, not the underlying books/scripts a corpus
        admission would actually emit; B4: wildguardmix's `database_rights_only` licenses
        the compilation right, not the individual contents).
      - `enrichment_licence_result` or `enrichment_plan` carrying a REFUSE/NONE ADMISSIBLE
        marker (B2: BeIR/cqadupstack's "R9 REFUSE at ingest" -- Stack Exchange's per-item
        attribution obligation is a structural refusal, not a caveat). Matched
        case-sensitively against the catalogue's own shouting-case convention -- see
        ENRICHMENT_REFUSAL_MARKER_RE's module-level comment.
      - a `redistribute` flag in FORBIDDEN_REDISTRIBUTE_FLAGS set true (`nd`:
        no-derivatives forbids training a derivative model on the data at all,
        independent of verdict/tier).
      - an UNRESOLVED `provenance_red_flags` entry, per RED_FLAG_RESOLUTION_RULE /
        `_unresolved_red_flags`. This is new: the round-2 review found google-research-
        datasets/paws itself refused by the factory's real (already-committed)
        RED_FLAGS_BLOCK_ADMISSION gate, because its catalogue row's red flag carries no
        `provenance_red_flags_resolution` entry -- paws is NOT a clean reference case
        today, it is refused pending that entry landing (TASK A). A red flag with a
        resolved=true resolution entry is surfaced in the detail string but does not gate.
    """
    row = catalogue_index.get(repo_id)
    if row is None:
        return CheckResult(
            "catalogue_structural_refusals",
            False,
            f"repo_id={repo_id!r} not found in the catalogue index -- refusing rather "
            "than admitting an entry this check cannot evaluate",
        )
    reasons: list[str] = []
    grant_scope = row.get("grant_scope")
    if grant_scope not in FULL_CONTENT_GRANT_SCOPES:
        reasons.append(
            f"grant_scope={grant_scope!r} does not cover full-content use "
            f"(admissible: {sorted(FULL_CONTENT_GRANT_SCOPES)})"
        )
    enrichment_result = str(row.get("enrichment_licence_result") or "")
    enrichment_plan = str(row.get("enrichment_plan") or "")
    if _has_enrichment_refusal_marker(enrichment_result, enrichment_plan):
        reasons.append(
            "enrichment_licence_result/enrichment_plan carries a REFUSE/NONE ADMISSIBLE "
            f"marker (enrichment_licence_result={enrichment_result!r}, "
            f"enrichment_plan={enrichment_plan!r})"
        )
    redistribute = row.get("redistribute") or {}
    forbidden_flags_set = sorted(
        flag for flag in FORBIDDEN_REDISTRIBUTE_FLAGS if redistribute.get(flag) is True
    )
    if forbidden_flags_set:
        reasons.append(
            f"redistribute flag(s) {forbidden_flags_set} forbid training/redistribution "
            "with no override (nd: no-derivatives forbids a trained derivative model)"
        )
    red_flags = list(row.get("provenance_red_flags") or [])
    red_flags_resolution = list(row.get("provenance_red_flags_resolution") or [])
    unresolved = _unresolved_red_flags(red_flags, red_flags_resolution)
    if unresolved:
        reasons.append(
            f"{len(unresolved)} unresolved provenance_red_flag(s) (no "
            f"provenance_red_flags_resolution entry with resolved=true): {unresolved!r}"
        )
    flags_note = f"; provenance_red_flags={red_flags!r}" if red_flags else ""
    if reasons:
        detail = "; ".join(reasons) + flags_note
        return CheckResult("catalogue_structural_refusals", False, detail)
    return CheckResult(
        "catalogue_structural_refusals",
        True,
        f"grant_scope={grant_scope!r}, no enrichment REFUSE marker, no forbidden "
        f"redistribute flags, no unresolved red flags{flags_note}",
    )


def check_policy_constants_drift(provenance: dict[str, Any]) -> CheckResult:
    """Check 5: `provenance.json`'s own `admission` block -- both the top-level
    `policy_version` AND the `constants` sub-object -- must agree with this tool's pinned
    `POLICY_VERSION`/`ADAPTER_POLICY_CONSTANTS` exactly. A drift here means the factory
    and this second-look tool are silently applying two different policies to the same
    admission decision -- exactly the split-brain B4 found, but caught automatically
    instead of by the next round of manual review.

    Three comparisons, reported independently rather than as one opaque "the dicts
    disagree" message: the record's top-level `admission.policy_version` against this
    tool's `POLICY_VERSION`; the record's two copies of the version against EACH OTHER
    (an internal inconsistency on the factory's side, not a drift from this tool); and
    the whole `constants` body against `ADAPTER_POLICY_CONSTANTS`. The version is a
    member of the compared dict as well as a sibling of it, because that is how the
    factory emits it -- see `ADAPTER_POLICY_CONSTANTS`'s own comment for why pinning
    only the other fourteen keys kept check 5 failing on every real record.

    Forward-compatible on purpose: a `provenance.json` with no `admission` block at all
    (a provenance.json fetched before the factory started emitting one) PASSES with a note
    that the check is not yet applicable -- it does not retroactively refuse a dataset
    already on disk for lacking a field the factory did not emit at fetch time.
    """
    if "admission" not in provenance:
        return CheckResult(
            "policy_constants_drift",
            True,
            "provenance.json carries no `admission` block (fetched before the factory "
            "started emitting one) -- drift check not yet applicable",
        )
    admission_block = provenance.get("admission")
    if not isinstance(admission_block, dict):
        return CheckResult(
            "policy_constants_drift",
            False,
            f"provenance.json's `admission` key is present but not an object: {admission_block!r}",
        )
    constants = admission_block.get("constants")
    if not isinstance(constants, dict):
        return CheckResult(
            "policy_constants_drift",
            False,
            "provenance.json carries an `admission` block but no `constants` sub-object",
        )
    mismatches: list[str] = []
    provenance_policy_version = admission_block.get("policy_version")
    if provenance_policy_version != POLICY_VERSION:
        mismatches.append(
            f"admission.policy_version={provenance_policy_version!r} disagrees with this "
            f"tool's own POLICY_VERSION={POLICY_VERSION!r}"
        )
    # The record carries the version twice on purpose -- once at the top of the
    # `admission` block for a reader, once inside `constants` so it cannot be dropped
    # from the compared dict. If those two disagree, the record is internally
    # inconsistent on the FACTORY's side, which is a different (and worse) fault than
    # drifting from this tool, so it is reported on its own terms rather than folded
    # into the whole-dict mismatch below.
    constants_policy_version = constants.get("ADMISSION_POLICY_VERSION")
    if constants_policy_version != provenance_policy_version:
        mismatches.append(
            f"the record disagrees with ITSELF: admission.policy_version="
            f"{provenance_policy_version!r} but admission.constants."
            f"ADMISSION_POLICY_VERSION={constants_policy_version!r}"
        )
    if constants != ADAPTER_POLICY_CONSTANTS:
        mismatches.append(
            f"admission.constants={constants!r} disagrees with this tool's own "
            f"ADAPTER_POLICY_CONSTANTS={ADAPTER_POLICY_CONSTANTS!r}"
        )
    if mismatches:
        return CheckResult("policy_constants_drift", False, "; ".join(mismatches))
    return CheckResult(
        "policy_constants_drift",
        True,
        f"provenance admission.policy_version and admission.constants both match this "
        f"tool's pinned policy exactly (policy_version={POLICY_VERSION!r})",
    )


def run_checklist(
    provenance: dict[str, Any],
    region: str,
    existing_shares: dict[str, int],
    region_tier: dict[str, str] | None = None,
    catalogue_index: dict[str, dict[str, Any]] | None = None,
) -> list[CheckResult]:
    """Run the admission checklist. `catalogue_index` (see `load_catalogue_index`) is
    optional so unit tests can exercise checks 1-3 in isolation with a synthetic
    provenance dict and no catalogue on disk; the CLI (`main`) always loads and passes
    one -- checks 4 and 5 are part of every real admission decision, not an opt-in extra.
    Paired together (both gated on `catalogue_index is not None`) because both are
    production-decision-time, second-look checks against the shared factory policy, unlike
    checks 1-3 which read only the provenance dict handed to this function.
    """
    tier_table = REGION_TIER if region_tier is None else region_tier
    verdict = provenance.get("verdict", "")
    provenance_group = provenance.get("provenance_group", "")
    added_count, estimated, measure_note = resolve_concentration_count(provenance)
    verification_status = provenance.get("verification_status", "")
    role = landing_role(provenance)
    if not contributes_to_train_concentration(role):
        largest_group, largest = largest_source(existing_shares)
        b1 = CheckResult(
            "b1_share",
            True,
            f"role={role!r} excluded from train concentration "
            f"({'/'.join(sorted(EXCLUDED_CONCENTRATION_ROLES))} do not count), "
            f"cap={B1_MAX_SHARE}; "
            f"largest source={largest_group!r} share={largest:.4f} cap={B1_MAX_SHARE}",
        )
    else:
        b1 = check_b1_share(
            provenance_group,
            added_count,
            existing_shares,
            estimated=estimated,
            measure_note=measure_note,
        )
    results = [
        check_licence_tier(verdict, region, tier_table),
        b1,
        check_verified(verification_status),
    ]
    if catalogue_index is not None:
        results.append(check_catalogue_structural_refusals(repo_id_of(provenance), catalogue_index))
        results.append(check_policy_constants_drift(provenance))
    return results


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def resolve_existing_shares_from_corpus_root(
    root: Path, exclude: Path | None = None
) -> dict[str, int]:
    """Derive `--existing-shares` by scanning every `provenance.json` under `root`
    (recursive), for `--corpus-root` -- the alternative to hand-typing the JSON.

    Each train landing's contribution is `resolve_concentration_count` (g24
    `active_train_set.train_files` when present, else `resolve_added_count`). Probe, aux,
    refuse, and held_seed landings are skipped. `exclude` is the candidate
    `provenance.json` under check -- compared by resolved path so a `--corpus-root` that
    contains the candidate does not count it once in the scan and again as `added_count`.

    A `provenance.json` that fails to parse (corrupt or a partial fetch) is skipped rather
    than crashing the whole scan; a dataset with no `provenance_group` on either the
    top level or the trimmed `catalogue_entry` is skipped the same way -- there is no
    group to attribute its count to. Neither omission is reported here (this is a best-
    effort disk scan, not a validation pass); a caller that needs to know what was
    skipped should scan `root` itself.
    """
    shares: dict[str, int] = {}
    seen: set[Path] = set()
    exclude_resolved = exclude.resolve() if exclude is not None else None
    for prov_path in sorted(root.rglob("provenance.json")):
        try:
            resolved = prov_path.resolve()
        except OSError:
            continue
        if resolved in seen:
            continue
        seen.add(resolved)
        if exclude_resolved is not None and resolved == exclude_resolved:
            continue
        try:
            provenance = _load_json(prov_path)
        except (json.JSONDecodeError, OSError):
            continue
        if not contributes_to_train_concentration(landing_role(provenance)):
            continue
        group = provenance.get("provenance_group") or provenance.get("catalogue_entry", {}).get(
            "provenance_group"
        )
        if not group:
            continue
        added_count, _estimated, _note = resolve_concentration_count(provenance)
        shares[str(group)] = shares.get(str(group), 0) + added_count
    return shares


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--provenance",
        required=True,
        type=Path,
        help="Path to the factory's provenance.json for one fetched dataset.",
    )
    parser.add_argument(
        "--region",
        required=True,
        help="Target CSD region name (e.g. retrieve, code, memory).",
    )
    parser.add_argument(
        "--existing-shares",
        default=None,
        help="JSON object: provenance_group -> current row/token count in the region's "
        "corpus, before this admission. No default -- pass --existing-shares '{}' "
        "EXPLICITLY to admit into a fresh region with zero existing rows (a silent "
        "default here previously forced every admission's B1 share to 1.0 and REFUSE, "
        "round-2 review non-blocking item). Mutually exclusive with --corpus-root.",
    )
    parser.add_argument(
        "--corpus-root",
        type=Path,
        default=None,
        help="Corpus root directory (e.g. the factory's fetch destination) to derive "
        "--existing-shares from by scanning every provenance.json under it -- the "
        "alternative to hand-typing the JSON. Mutually exclusive with --existing-shares.",
    )
    parser.add_argument(
        "--catalogue",
        type=Path,
        default=DEFAULT_CATALOGUE_PATH,
        help="Path to the full dataset-factory catalogue JSON (schema "
        "csd-dataset-factory-catalogue/v1), for check 4's second, independent structural-"
        "refusal look. Defaults to docs/design/datasets/catalogue-2026-09-03.json in this "
        "repo. Pass --no-catalogue-check to skip checks 4 and 5 entirely.",
    )
    parser.add_argument(
        "--no-catalogue-check",
        action="store_true",
        help="Skip checks 4 and 5 (catalogue structural refusals, policy constants "
        "drift). Only for the checklist's checks 1-3 against a provenance.json in "
        "isolation -- production admission decisions should keep checks 4 and 5 on.",
    )
    args = parser.parse_args(argv)

    if args.existing_shares is not None and args.corpus_root is not None:
        parser.error("pass only one of --existing-shares or --corpus-root, not both")
        return 2  # pragma: no cover - argparse.error already exits
    if args.existing_shares is None and args.corpus_root is None:
        parser.error(
            "one of --existing-shares or --corpus-root is required -- pass "
            "--existing-shares '{}' explicitly to admit into a fresh region with zero "
            "existing rows, or --corpus-root to derive shares from disk"
        )
        return 2  # pragma: no cover - argparse.error already exits

    provenance = _load_json(args.provenance)
    if args.corpus_root is not None:
        existing_shares = resolve_existing_shares_from_corpus_root(
            args.corpus_root, exclude=args.provenance
        )
    else:
        try:
            existing_shares = json.loads(args.existing_shares)
        except json.JSONDecodeError as exc:
            parser.error(f"--existing-shares is not valid JSON: {exc}")
            return 2  # pragma: no cover - argparse.error already exits

    catalogue_index = None if args.no_catalogue_check else load_catalogue_index(args.catalogue)

    results = run_checklist(
        provenance, args.region, existing_shares, catalogue_index=catalogue_index
    )

    repo_id = repo_id_of(provenance)
    print(f"Admission checklist: {repo_id} -> region {args.region!r}")
    all_passed = True
    for result in results:
        status = "PASS" if result.passed else "FAIL"
        all_passed = all_passed and result.passed
        print(f"  [{status}] {result.name}: {result.detail}")
    added_count, _estimated, _note = resolve_concentration_count(provenance)
    post_shares = dict(existing_shares)
    if contributes_to_train_concentration(landing_role(provenance)):
        group = str(provenance.get("provenance_group") or "")
        post_shares[group] = post_shares.get(group, 0) + added_count
    largest_group, largest = largest_source(post_shares)
    print(f"Largest source: {largest_group or '<none>'} share={largest:.4f} cap={B1_MAX_SHARE}")
    print(f"Result: {'ADMIT' if all_passed else 'REFUSE'}")
    return 0 if all_passed else 1


if __name__ == "__main__":
    sys.exit(main())
