#!/usr/bin/env python3
"""Mirror `docs/`'s markdown tree into a Forgejo wiki checkout.

WHY THIS SCRIPT EXISTS
CogSynDelta's docs pipeline used to build a pdoc + hand-copied `_site/` and deploy it to
GitHub Pages (`.github/workflows/docs.yml`, jobs `build`/`deploy`). Forgejo Actions
(`git.vectorweight.com`) resolves bare action names against `data.forgejo.org`, which does
not carry `actions/configure-pages`, `actions/upload-pages-artifact`, or
`actions/deploy-pages` -- every Pages run failed at setup. The operator's call: deploy to
the self-hosted Forgejo wiki instead. This module is the mirroring logic; the actual
clone/commit/push of the wiki repository is a git-shell job in
`.github/workflows/docs.yml` (job `wiki`), not this script -- this script only turns a
`docs/` tree plus a target directory into the wiki page set that belongs in it, which is
what makes `--dry-run` and `--out DIR` meaningful without ever touching the real wiki.

WHAT GETS MIRRORED
Every `*.md` file under `docs/` (recursively) becomes one wiki page, except the top-level
`docs/README.md`, which is instead the SOURCE for the generated `Home.md` (see below) --
mirroring it a second time under its own page name would just duplicate Home.md. Every
image file under `docs/` (png/jpg/jpeg/gif/svg/webp/bmp/ico) is copied alongside the pages
it is referenced from, under the same flattened name. No other file type under `docs/` is
copied into the wiki; links to them are rewritten to point at the source repository
instead (see "LINK REWRITING" below) -- there is nowhere in a markdown-only wiki for a
`.json`/`.pdf`/`.tar.gz`/`.py` file to live, and pretending otherwise would silently drop
content type it cannot render.

PAGE-NAME SCHEME
A page name is the file's path relative to `docs/`, with each path separator replaced by
`--` and internal whitespace in each path segment collapsed to `-` (wiki filenames should
not contain spaces even though several source docs' filenames do):

    docs/design/REGION-TAXONOMY-AND-INTERCONNECT.md -> design--REGION-TAXONOMY-AND-INTERCONNECT.md
    docs/plain/01-what-csd-is.md                     -> plain--01-what-csd-is.md
    docs/ARCHITECTURE.md                             -> ARCHITECTURE.md
    docs/adr/archive/README.md                       -> adr--archive--README.md

This is purely path-derived, so it needs no changes for the `docs/plain|technical|
foundations` reader-tracks layout landing on another branch, or for any other future
subdirectory -- it falls out of the same rule. Images use the identical flattening,
keeping their original extension.

LINK REWRITING
Every markdown link/image target `[text](target)` / `![alt](target)` is resolved relative
to its source file's directory to a repo-root-relative path, then classified:
  - an absolute URL (has a scheme, e.g. `https://...`, `mailto:...`) or a same-page anchor
    (`#section`) is left untouched;
  - a path that resolves under `docs/` and ends in `.md` is rewritten to the wiki page
    name for that path;
  - a path that resolves under `docs/` and is an image (see extensions above) is
    rewritten to the flattened asset filename copied alongside;
  - anything else (a non-markdown file under `docs/`, or any path outside `docs/`
    entirely, including a bare directory link) is rewritten to the source-repository blob
    URL `<repo-url>/src/branch/<branch>/<path>`.
Any `#anchor` suffix on the original target (a heading link, or a source-file line anchor
like `#L83`) is preserved on both a rewritten wiki-page link and a rewritten blob URL.
A link this script cannot resolve within the repository (e.g. one that walks above the
repository root via `../..`) is left exactly as written rather than guessed at.

Rewriting is skipped for lines inside fenced code blocks (``` / ~~~) so example command
lines that happen to look like markdown links are not touched.

MARKING AND STALE-PAGE REMOVAL
Every page this script writes -- mirrored docs, `Home.md`, `_Sidebar.md` -- gets
`<!-- generated by scripts/docs_to_wiki.py from <sha> -->` as its first line. On each run,
any `*.md` file already present in `--out` that is NOT part of the current generated set
is removed IF AND ONLY IF its first few lines carry that marker; a wiki page without the
marker is assumed hand-written and is never touched, matching or not. Generated image
assets are additive-only (never pruned) -- there is currently nothing in `docs/` to copy,
and an image cannot carry an HTML comment marker, so auto-deleting them has no safe
detection mechanism yet.

Usage:
    scripts/docs_to_wiki.py --out DIR                 # write the mirror into DIR
    scripts/docs_to_wiki.py --out DIR --dry-run        # compute and report, write nothing
    scripts/docs_to_wiki.py --out DIR --sha abc1234    # embed an explicit marker sha

Exit codes: 0 ok; 2 `--docs-dir` is not a directory.
"""

from __future__ import annotations

import argparse
import posixpath
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

MARKER_PREFIX = "<!-- generated by scripts/docs_to_wiki.py from "
MARKER_SUFFIX = " -->"

DEFAULT_REPO_URL = "https://git.vectorweight.com/tzervas/CogSynDelta"
DEFAULT_BRANCH = "main"

IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp", ".bmp", ".ico"}

# Matches `[text](target)` and `![alt](target)`, with an optional `"title"` after the
# target. `target` itself cannot contain unescaped whitespace or `)` -- true of every link
# in this docs corpus (verified: no markdown link target contains a raw space).
_MD_LINK_RE = re.compile(
    r'(?P<bang>!?)\[(?P<text>[^\]]*)\]\((?P<target>[^)\s]+)(?P<title>\s+"[^"]*")?\)'
)
_FENCE_RE = re.compile(r"^\s*(```|~~~)")
_SCHEME_RE = re.compile(r"^[a-zA-Z][a-zA-Z0-9+.-]*:")


def marker_line(sha: str) -> str:
    """Build the generator marker comment embedded as the first line of every page."""
    return f"{MARKER_PREFIX}{sha}{MARKER_SUFFIX}"


def is_marker_line(line: str) -> bool:
    """True if `line` is a (any-sha) generator marker comment."""
    stripped = line.strip()
    return stripped.startswith(MARKER_PREFIX) and stripped.endswith(MARKER_SUFFIX)


def sanitize_segment(segment: str) -> str:
    """Collapse whitespace runs in one path segment to a single `-`.

    Several source filenames under docs/ contain real spaces (research-paper titles
    copied in verbatim); wiki page/asset filenames should not.
    """
    return re.sub(r"\s+", "-", segment.strip())


def flatten_docs_path(doc_rel_repo: str) -> str:
    """`docs/<a>/<b>.ext` -> `<a>--<b>.ext`; `docs/<c>.ext` -> `<c>.ext`.

    `doc_rel_repo` must be a repo-root-relative posix path starting with `docs/`.
    """
    if not doc_rel_repo.startswith("docs/"):
        raise ValueError(f"not under docs/: {doc_rel_repo!r}")
    rest = doc_rel_repo[len("docs/") :]
    parts = [sanitize_segment(p) for p in rest.split("/") if p]
    return "--".join(parts)


def slugify(text: str) -> str:
    """A GFM-ish heading slug: lowercase, non-word chars dropped, spaces to `-`."""
    s = text.strip().lower()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"\s+", "-", s)
    return s


@dataclass
class RewriteResult:
    text: str
    samples: list[tuple[str, str, str]] = field(default_factory=list)  # (original, rewritten, kind)


def _is_untouched_target(target: str) -> bool:
    """True for a target that must never be rewritten: empty, `//host/...`, a same-page
    anchor (`#...`), or anything with a URL scheme (`https:`, `mailto:`, ...).
    """
    return (
        not target
        or target.startswith("#")
        or target.startswith("//")
        or bool(_SCHEME_RE.match(target))
    )


def classify_and_resolve(
    source_doc_rel: str, raw_target: str, *, repo_url: str, branch: str
) -> tuple[str, str] | None:
    """Resolve one link target relative to `source_doc_rel`.

    Returns `(rewritten_target, kind)` where `kind` is `"wiki"`, `"asset"`, or `"blob"`,
    or `None` if the link should be left exactly as written (external URL, same-page
    anchor, or a path this script cannot resolve inside the repository).
    """
    target = raw_target.strip()
    if _is_untouched_target(target):
        return None

    path_part, has_anchor, anchor = target.partition("#")
    if not path_part:
        return None  # target was anchor-only after all (e.g. "./#foo"); same-page.

    is_dir_link = path_part.endswith("/")
    source_dir = posixpath.dirname(source_doc_rel)
    if path_part.startswith("/"):
        resolved = posixpath.normpath(path_part.lstrip("/"))
    else:
        resolved = posixpath.normpath(posixpath.join(source_dir, path_part))
    if is_dir_link:
        resolved = resolved.rstrip("/") + "/"

    if resolved == ".." or resolved.startswith("../"):
        # Cannot resolve within the repository -- leave the original link alone.
        return None

    resolved_no_slash = resolved.rstrip("/")
    ext = posixpath.splitext(resolved_no_slash)[1].lower()

    if resolved_no_slash.startswith("docs/") and ext == ".md":
        page = flatten_docs_path(resolved_no_slash)
        return (f"{page}#{anchor}" if has_anchor else page, "wiki")
    if resolved_no_slash.startswith("docs/") and ext in IMAGE_EXTENSIONS:
        return (flatten_docs_path(resolved_no_slash), "asset")

    url = f"{repo_url}/src/branch/{branch}/{resolved}"
    return (f"{url}#{anchor}" if has_anchor else url, "blob")


def rewrite_links(text: str, source_doc_rel: str, *, repo_url: str, branch: str) -> RewriteResult:
    """Rewrite every resolvable markdown link/image target in `text`.

    Lines inside fenced code blocks (``` or ~~~) are passed through unchanged.
    """
    samples: list[tuple[str, str, str]] = []
    out_lines: list[str] = []
    in_fence = False

    def _sub(m: re.Match[str]) -> str:
        target = m.group("target")
        result = classify_and_resolve(source_doc_rel, target, repo_url=repo_url, branch=branch)
        if result is None:
            return m.group(0)
        new_target, kind = result
        # Record every resolved link, even one whose rewritten text is identical to the
        # original (a bare top-level filename flattens to itself) -- broken-link
        # detection in build_mirror() needs every classified "wiki" link, not just the
        # ones whose text visibly changed.
        samples.append((target, new_target, kind))
        title = m.group("title") or ""
        return f"{m.group('bang')}[{m.group('text')}]({new_target}{title})"

    for line in text.splitlines(keepends=True):
        if _FENCE_RE.match(line):
            in_fence = not in_fence
            out_lines.append(line)
            continue
        if in_fence:
            out_lines.append(line)
            continue
        out_lines.append(_MD_LINK_RE.sub(_sub, line))

    return RewriteResult("".join(out_lines), samples)


def git_short_sha(repo_path: Path) -> str | None:
    """`git rev-parse --short=12 HEAD` from within `repo_path`, or None on any failure."""
    try:
        out = subprocess.run(
            ["git", "-C", str(repo_path), "rev-parse", "--short=12", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
            timeout=10,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    sha = out.stdout.strip()
    return sha or None


@dataclass
class MirrorResult:
    pages: dict[str, str]  # page filename -> full file content (marker + body)
    assets: dict[str, bytes]  # asset filename -> raw bytes
    samples: list[tuple[str, str, str, str]]  # (source doc, original target, rewritten, kind)
    broken_wiki_links: list[tuple[str, str]]  # (source doc, dangling page name)


def build_mirror(docs_dir: Path, *, sha: str, repo_url: str, branch: str) -> MirrorResult:
    """Compute the full set of generated wiki pages and assets from `docs_dir`.

    Does not touch the filesystem outside `docs_dir` (read-only) -- writing is the
    caller's job, so this same computation backs both `--dry-run` and a real write.
    """
    md_files = sorted(p for p in docs_dir.rglob("*.md") if p.is_file())
    image_files = sorted(
        p for p in docs_dir.rglob("*") if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS
    )

    pages: dict[str, str] = {}
    doc_page_pairs: list[tuple[str, str]] = []
    samples: list[tuple[str, str, str, str]] = []

    top_level_readme = docs_dir / "README.md"

    for md in md_files:
        if md == top_level_readme:
            continue  # becomes Home.md's source instead of its own page
        doc_rel_repo = "docs/" + md.relative_to(docs_dir).as_posix()
        page_name = flatten_docs_path(doc_rel_repo)
        body = md.read_text(encoding="utf-8")
        rewritten = rewrite_links(body, doc_rel_repo, repo_url=repo_url, branch=branch)
        content = marker_line(sha) + "\n\n" + rewritten.text
        if not content.endswith("\n"):
            content += "\n"
        pages[page_name] = content
        doc_page_pairs.append((doc_rel_repo, page_name))
        for orig, new, kind in rewritten.samples:
            samples.append((doc_rel_repo, orig, new, kind))

    home_content, sidebar_content = _build_home_and_sidebar(
        doc_page_pairs, docs_dir, sha=sha, repo_url=repo_url, branch=branch
    )
    pages["Home.md"] = home_content
    pages["_Sidebar.md"] = sidebar_content

    assets: dict[str, bytes] = {}
    for img in image_files:
        doc_rel_repo = "docs/" + img.relative_to(docs_dir).as_posix()
        assets[flatten_docs_path(doc_rel_repo)] = img.read_bytes()

    generated_names = set(pages)
    broken: list[tuple[str, str]] = []
    for source_doc, _orig, new, kind in samples:
        if kind != "wiki":
            continue
        page_part = new.split("#", 1)[0]
        if page_part not in generated_names:
            broken.append((source_doc, page_part))

    return MirrorResult(pages=pages, assets=assets, samples=samples, broken_wiki_links=broken)


def _build_home_and_sidebar(
    doc_page_pairs: list[tuple[str, str]],
    docs_dir: Path,
    *,
    sha: str,
    repo_url: str,
    branch: str,
) -> tuple[str, str]:
    readme = docs_dir / "README.md"
    if readme.is_file():
        body = readme.read_text(encoding="utf-8")
        home_body = rewrite_links(body, "docs/README.md", repo_url=repo_url, branch=branch).text
    else:
        sections: dict[str, list[tuple[str, str]]] = {}
        for doc_rel_repo, page_name in doc_page_pairs:
            rest = doc_rel_repo[len("docs/") :]
            section = rest.split("/", 1)[0] if "/" in rest else "Top-level"
            sections.setdefault(section, []).append((doc_rel_repo, page_name))

        lines = [
            "# CogSynDelta Documentation",
            "",
            "Generated index of `docs/` (no `docs/README.md` was present to build this from).",
            "",
        ]
        for section in sorted(sections, key=lambda s: (s != "Top-level", s.lower())):
            lines.append(f"## {section}")
            lines.append("")
            for doc_rel_repo, page_name in sorted(sections[section]):
                title = Path(doc_rel_repo).stem
                lines.append(f"- [{title}]({page_name})")
            lines.append("")
        home_body = "\n".join(lines).rstrip() + "\n"

    home_content = marker_line(sha) + "\n\n" + home_body
    if not home_content.endswith("\n"):
        home_content += "\n"

    section_names: list[str] = []
    for doc_rel_repo, _page_name in doc_page_pairs:
        rest = doc_rel_repo[len("docs/") :]
        section = rest.split("/", 1)[0] if "/" in rest else "Top-level"
        if section not in section_names:
            section_names.append(section)
    section_names.sort(key=lambda s: (s != "Top-level", s.lower()))

    sidebar_lines = [marker_line(sha), "", "* [Home](Home.md)"]
    for section in section_names:
        sidebar_lines.append(f"* [{section}](Home.md#{slugify(section)})")
    sidebar_content = "\n".join(sidebar_lines) + "\n"

    return home_content, sidebar_content


def prune_stale(out_dir: Path, generated_names: set[str], *, dry_run: bool) -> list[str]:
    """Remove `*.md` files in `out_dir` that are stale generated pages.

    A file is removed only if it is (a) not part of the current generated set and (b)
    carries the generator marker on one of its first few lines -- a hand-written wiki
    page never carries that marker and is never touched.
    """
    removed: list[str] = []
    if not out_dir.is_dir():
        return removed
    for existing in sorted(out_dir.glob("*.md")):
        if existing.name in generated_names:
            continue
        try:
            head = existing.read_text(encoding="utf-8", errors="replace").splitlines()[:3]
        except OSError:
            continue
        if any(is_marker_line(line) for line in head):
            removed.append(existing.name)
            if not dry_run:
                existing.unlink()
    return removed


def write_mirror(out_dir: Path, mirror: MirrorResult) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, content in mirror.pages.items():
        (out_dir / name).write_text(content, encoding="utf-8")
    for name, data in mirror.assets.items():
        (out_dir / name).write_bytes(data)


def _print_report(
    mirror: MirrorResult, removed: list[str], *, dry_run: bool, sample_count: int
) -> None:
    print(f"pages: {len(mirror.pages)}")
    print(f"assets: {len(mirror.assets)}")
    print(f"removed stale generated pages: {len(removed)}")
    for name in removed:
        print(f"  - {name}")
    print(f"rewritten links (showing up to {sample_count} of {len(mirror.samples)}):")
    for source_doc, orig, new, kind in mirror.samples[:sample_count]:
        print(f"  [{kind}] {source_doc}: {orig!r} -> {new!r}")
    marker_ok = all(is_marker_line(content.splitlines()[0]) for content in mirror.pages.values())
    print(f"all generated pages carry the marker: {marker_ok}")
    if mirror.broken_wiki_links:
        print(
            f"WARNING: {len(mirror.broken_wiki_links)} internal link(s) point at a page not in this mirror:"
        )
        for source_doc, page in mirror.broken_wiki_links[:sample_count]:
            print(f"  {source_doc} -> {page}")
    if dry_run:
        print("(dry-run: no files were written or removed)")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else "")
    parser.add_argument(
        "--docs-dir", default="docs", help="path to the docs/ tree to mirror (default: docs)"
    )
    parser.add_argument(
        "--out", required=True, help="wiki checkout (or scratch) directory to write into"
    )
    parser.add_argument(
        "--sha",
        default=None,
        help="sha embedded in the generator marker (default: git rev-parse --short=12 HEAD in --docs-dir)",
    )
    parser.add_argument(
        "--repo-url",
        default=DEFAULT_REPO_URL,
        help=f"source repository URL for blob links (default: {DEFAULT_REPO_URL})",
    )
    parser.add_argument(
        "--branch",
        default=DEFAULT_BRANCH,
        help=f"source branch for blob links (default: {DEFAULT_BRANCH})",
    )
    parser.add_argument("--dry-run", action="store_true", help="compute and report; write nothing")
    parser.add_argument(
        "--sample-count",
        type=int,
        default=8,
        help="how many rewritten-link samples to print (default: 8)",
    )
    args = parser.parse_args(argv)

    docs_dir = Path(args.docs_dir).resolve()
    if not docs_dir.is_dir():
        print(f"error: --docs-dir is not a directory: {docs_dir}", file=sys.stderr)
        return 2

    sha = args.sha or git_short_sha(docs_dir) or "unknown"

    mirror = build_mirror(docs_dir, sha=sha, repo_url=args.repo_url, branch=args.branch)

    out_dir = Path(args.out)
    removed = prune_stale(out_dir, set(mirror.pages), dry_run=args.dry_run)

    if not args.dry_run:
        write_mirror(out_dir, mirror)

    _print_report(mirror, removed, dry_run=args.dry_run, sample_count=args.sample_count)
    return 0


if __name__ == "__main__":
    sys.exit(main())
